### ISSUE TITLE
As year of 2020, suggest to upgrade kingly dependency from node version '6.3.0' only to compatible higher version.

### ISSUE THREAD

**Issue by leopku** [brucou/kingly#7]
Thanks for this awesome lib.
I was in trouble while I trying kingly.
```
❯❯❯ yarn add react-state-driven
...
error kingly@0.18.2: The engine "node" is incompatible with this module. Expected version "6.3.0". Got "12.8.0"
error Found incompatible module.
```

Can I suggest to upgrade node dependency version to some like `"node": ">= 6.3.0"` or else?

Thanks again.

**Comment by brucou** [comment]
Thanks for the notification, I will have a look. Kingly is now v0.28. I have to update react-state-driven with the new changes. I will have a look at the node version too.

**Comment by brucou** [comment]
@leopku You can always experiment with the codesandbox playground. This one working example that you can fork: https://codesandbox.io/s/ym8vpqm7m9?file=/src/index.js

Also, in codesandbox, you have a `File -> Export to zip` option that packages the sandbox configuration so you can run it locally. You may be more lucky this way. I am continunig to investigate

**Comment by leopku** [comment]
@brucou Thanks for reply so quickly.

I still can't add react-state-driven to my project.

## yarn add
```
❯❯❯ yarn add react-state-driven                                                          ✘ 1 master ✱ ◼
yarn add v1.17.3
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error kingly@0.18.2: The engine "node" is incompatible with this module. Expected version "6.3.0". Got "12.8.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

## manually add to package.json `"react-state-driven": "0.8.0",` then run `yarn install`
```
yarn install                                                                             master ✱ ◼
yarn install v1.17.3
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error state-transducer-testing@0.11.3: The engine "node" is incompatible with this module. Expected version "6.3.0". Got "12.8.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by brucou** [comment]
Ok I see the issue is probably with the package.json of Kingly. It has [this content](https://github.com/brucou/kingly/blob/master/package.json#L44):

```json
{
...
  "engines": {
    "node": "6.3.0"
  },
...
}
```

I will try to see what is the best way to proceed tomorrow. Maybe I can publish a new minor version of Kingly with `"node": ">= 6.3.0"` and then anotehr minor version of react-state-driven. The other alternative is to do the same but also update directly react-state-driven to the latest version of kingly but that may take one more day.

Thanks for your patience

**Comment by brucou** [comment]
Alright, can you try this: https://codesandbox.io/s/ym8vpqm7m9?file=/src/helpers.js
This has the latest Kingly and the latest `<Machine/>` component from `react-state-driven`  with the node configuration removed so there should not be any node error in principle.

Let me know if it works on your side.

**Comment by brucou** [comment]
I refactored the codesandbox so it is more React-like and uses JSX. That should help if you are not used to react-hyperscript. Also refactored the screen and error management. i will soon simplify the API in 0.11  by removing one or two parameters

**Comment by leopku** [comment]
Thanks for your kindness.

`react-state-driven` still depend on `state-transducer-testing` which also be limited with node 6.3.0.

I made a [PR](/brucou/state-transducer-testing/pull/1) to fixed it.

**Comment by brucou** [comment]
PR accepted. Let me know if any questions on the library or further issues. It is very interesting for me to get feedback. I will review the Machine tests tomorrow. It should be based on an older version of the library so that has to be updated too.

**Comment by leopku** [comment]
Thanks a lot, @brucou 

But it failed again because of `graph-adt@0.7.0` expect version 6.3.0.

It's need to update `graph-adt`.

**Comment by brucou** [comment]
Just did it and update react-state-driven to 0.10.7. Can you please try again? hopefully this time it works. I will need to revisit all the build configuration over the week-end... sorry for the inconvenience.

**Comment by leopku** [comment]
Hi @brucou ,

Did `react-state-driven@0.10.7` dependent `state-transducer-testing@0.11.4` or `state-transducer-testing@0.11.3`? 

The master branch was `0.10.6` and `"state-transducer-testing": "^0.11.3"` was stay the place of dependency. 

It should be upgrade `state-transducer-testing` to `^0.11.4` and publishing version `0.11.4` of `state-transducer-testing` should be also desired.

**Comment by leopku** [comment]
Hi @brucou ,

The package `state-transducer` which also dependent by `state-transducer-testing` locked the node version too. 

The repo of `state-transducer` had been moved to `kingly`. It should also be upgraded to make   all of this work.

**Comment by brucou** [comment]
I rmoved the dependency on state-transducer-testing and graph-adt. can you try again?

**Comment by leopku** [comment]
Hi brucou,

`0.10.8` can been added successfully. I would test it functionally.

Thanks very very much for wasting your weekend time.

**Comment by brucou** [comment]
You are not wasting anything at all, it is my responsability to provide software that works and can be used. You reporting your issues is helpful for all those who have encountered the same errors than you and now no longer will have your issues thanks to you. So please continue to report any issue you find, and questions you have.

**Comment by brucou** [comment]
I'l lleave this open for a few days before closing it in case there is anything else occuring.

**Comment by brucou** [comment]
> 0.10.8 can been added successfully. I would test it functionally.
How did that go? Anything I can help with?

**Comment by leopku** [comment]
Sorry for leaving this because of other works.

Dependency issue was fixed now.

But [react example](https://codesandbox.io/s/yklw04n7qj?file=/src/properties.js:9-18) was broken because of changes like `state-transducer` was deprecated. I'm still struggling with it.

**Comment by brucou** [comment]
Here is the react example with dependencies updated to Kingly: https://codesandbox.io/s/flickr-search-app-with-kingly-qivl3

**Comment by leopku** [comment]
It works. Thank yout, @brucou .

**Comment by brucou** [comment]
@leopku readme for react-state-driven has been updated to reflect the changes in the new version. The main documentation site has also been updated: https://brucou.github.io/documentation/v1/int-react/index.html

**Comment by leopku** [comment]
> https://brucou.github.io/documentation/v1/int-react/index.html

Big thanks for so nice and detailed document.
