### ISSUE TITLE
yed2kingly not working

### ISSUE THREAD

**Issue by Sheldonfrith** [brucou/kingly#9]
EDIT: Whoops! I didn't see that yed2kingly had its own public repo, I will repost this issue there. Feel free to delete it.

I've installed yed2kingly with npm, run the command 
```bash
node ${path to yed2kingly in node_modules}/index.js ${path to my graphml file}
```
But nothing happens, no error output of any kind.
Also in the Readme for yed2kingly it says you are supposed to run it with the 'mode' command, but I assumed this was a typo and you meant 'node'?

Thanks! 
Just getting started with Kingly, if it does what I think it does its awesome and will surely become very popular!

**Comment by Sheldonfrith** [comment]
Update: After looking at the source code I've modified the command to 
```bash
node ${path to node_modules/yed2kingly/bin/yed2kingly} ${path to my graphml file}
```
However now I'm getting 'Error: Cannot find module './yedEdgeLabelGrammar.js'

I will keep looking through the source code to see if I can figure out what I'm doing wrong... but even if I end up figuring it out I would recommend updating the README so that others don't have the same issues as I do.

**Comment by Sheldonfrith** [comment]
Update: As the error above suggested, it appears the yedEdgeLabelGrammer.js file is missing from the package...

**Comment by brucou** [comment]
Going to have a look today. Sorry for the inconvenience and thank you for reporting.
